---

- name: Setup the Git repo
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_branch }}"
    dest: "{{ project_path }}"
    accept_hostkey: yes
    recursive: no
    force: yes
  when: setup_git_repo
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git