---

- name: Install packages required by the Django app inside virtualenv
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv_path }}"

- name: Create settings
  template:
    src: "{{ settings_template }}"
    dest: "{{ application_path }}/{{ configuration_name }}/settings/prod.py"
    backup: true
  tags: django.create_settings

- name: Migrate schemas
  shell: "{{ virtualenv_path }}/bin/python manage.py migrate --settings {{ django_settings_file }}"
  args:
    chdir: "{{ application_path }}"
  tags: django.migrate

- name: Clean collectstatic dir
  file:
    path: "{{ virtualenv_path }}/{{ project_name }}/static"
    state: absent

- name: Run Django collectstatic
  shell: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/{{ project_name }}/manage.py collectstatic --settings {{ django_settings_file }}"
  args:
    chdir: "{{ application_path }}"
  tags: django.collectstatic

- name: Create Django superUser
  shell: "echo \"from django.contrib.auth.models import User; User.objects.filter(username='{{pirra_su_username}}').exists() or User.objects.create_superuser('{{pirra_su_username}}', '{{pirra_su_mail}}', '{{pirra_su_pass}}')\" |{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/{{ project_name }}/manage.py shell --settings {{ django_settings_file }}"
  args:
    chdir: "{{ application_path }}"
  tags: django.createsuperuser

- name: Create Empresa Data
  shell: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/{{ project_name }}/manage.py init_empresa {{ pirra_cuit }} \"{{ pirra_nombre_empresa }}\" --settings {{ django_settings_file }}"
  args:
    chdir: "{{ application_path }}"
  tags: django.init_empresa

- name: Load Comprobantes Afip Data
  shell: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/{{ project_name }}/manage.py loaddata afip/fixtures/initial_data.json --settings {{ django_settings_file }}"
  args:
    chdir: "{{ application_path }}"
  tags: django.loaddata
